apiVersion: skaffold/v2beta18
kind: Config
build:
  local:
    concurrency: 0
requires:
  - path: ./monitoring
  - path: ./src/backend
  - path: ./src/frontend
profiles:
- name: cloudbuild
  build:
    googleCloudBuild: {}