apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: monitoring
data:
  alerts.yml: |
    groups:
    - name: GuestbookAlerts
      rules:
      - alert: HighCPUUsage
        expr: sum(rate(container_cpu_usage_seconds_total{container!="POD",pod=~"python-guestbook-.*"}[5m])) by (pod) > 0.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected"
          description: "Pod {{ $labels.pod }} has high CPU usage: {{ $value }}"

      - alert: HighMemoryUsage
        expr: sum(container_memory_working_set_bytes{container!="POD",pod=~"python-guestbook-.*"}) by (pod) > 200000000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage detected"
          description: "Pod {{ $labels.pod }} has high memory usage: {{ $value }} bytes"

      - alert: PodRestart
        expr: changes(kube_pod_status_ready{condition="true",pod=~"python-guestbook-.*"}[15m]) > 3
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Pod restarting frequently"
          description: "Pod {{ $labels.pod }} has restarted {{ $value }} times in the last 15 minutes"

      - alert: HighLatency
        expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=~"python-guestbook-.*"}[5m])) by (le)) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High latency detected"
          description: "95th percentile latency is {{ $value }} seconds"

      - alert: HighErrorRate
        expr: sum(rate(http_requests_total{job=~"python-guestbook-.*",status=~"5.."}[5m])) / sum(rate(http_requests_total{job=~"python-guestbook-.*"}[5m])) > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }}"
