apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-guestbook-frontend
  labels:
    app: python-guestbook
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-guestbook
      tier: frontend
  template:
    metadata:
      labels:
        app: python-guestbook
        tier: frontend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      initContainers:
      - name: init-backend-ready
        image: curlimages/curl:7.82.0
        command: ['sh', '-c']
        args:
          - echo "Waiting for backend at python-guestbook-backend:8080 to be ready...";
          - until curl --connect-timeout 2 -s http://python-guestbook-backend:8080/messages; do echo "Waiting for backend - sleep 2"; sleep 2; done
      containers:
      - name: frontend
        image: python-guestbook-frontend
        ports:
        - name: http-server
          containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: GUESTBOOK_API_ADDR
          value: python-guestbook-backend:8080
        # Elastic APM environment variables
        - name: ELASTIC_APM_SERVER_URL
          value: "http://apm-server.monitoring:8200"
        - name: ELASTIC_APM_SERVICE_NAME
          value: "python-guestbook-frontend"
        - name: ELASTIC_APM_ENVIRONMENT
          value: "development"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /
            port: http-server
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: http-server
          initialDelaySeconds: 15
          periodSeconds: 10